apiVersion: v1
kind: Service
metadata:
 labels:
 run: nginx-frontend
 name: nginx-frontend
spec:
 selector:
 run: nginx-frontend
 ports:
 - name: http
 port: 80
 protocol: TCP
 targetPort: 80
 - name: https
 port: 443
154 Services, Load Balancing, and External DNS
 protocol: TCP
 targetPort: 443
 type: NodePort
