apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
        containers:
        - name: app1-nginx
          image: 322340676524.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
          ports:
          - containerPort: 80
        imagePullSecrets:
        - name: regcred
