apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    app: busybox
    purpose: emptydir-demo
spec:
  volumes:
  - name: cache-volume
    emptyDir: {}
  containers:
  - name: container-1
    image: centos
    env:
      - name: TZ
        value: Asia/Kolkata
    command:
      - "bin/bash"
      - "-c"
      - "date >> /cache/date.txt; sleep 1000"
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - name: container-2
    image: centos
    env:
      - name: TZ
        value: Asia/Kolkata
    command:
      - "bin/bash"
      - "-c"
      - "cat /cache/date.txt; sleep 1000"
    volumeMounts:
    - mountPath : /cache
      name: cache-volume